### ISSUE TITLE
ModuleNotFoundError: No module named 'bs4'

### ISSUE THREAD

**Issue by dagostinelli** [timheap/flask-saml2#6]
I was trying to run the samples.  After a fresh install in a fresh virtualenv and then after running `pip install -e .` 

then:
```
$ ./examples/idp.py
Traceback (most recent call last):
  File "./examples/idp.py", line 8, in <module>
    from tests.idp.base import CERTIFICATE, PRIVATE_KEY, User
  File "/mnt/c/Users/user_name/source/repos/flask-saml2/tests/idp/base.py", line 10, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'
```

Solution:
`$ pip install bs4`

Looks like the setup.py is missing something.

**Comment by timheap** [comment]
Ah, you're right! The README should also include `pip install -r tests/requirements.txt` to run the examples. I'll fix that now.

**Comment by timheap** [comment]
Thanks!
